In [6]:
import pandas as pd
df = pd.read_csv("food_delivery_50_rows.csv")
df.head()

,user_id,city,order_time,restaurant_type,item_ordered,cart_size,recommended_item
0,user_1,Mumbai,lunch,fastfood,burger,4,fries
1,user_2,Mumbai,night,south indian,dosa,1,ice cream
2,user_3,Delhi,lunch,pizza,pizza,3,coke
3,user_4,Mumbai,night,indian,biryani,1,raita
4,user_5,Bangalore,night,fastfood,burger,3,fries

In [8]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           50 non-null     object
 1   city              50 non-null     object
 2   order_time        50 non-null     object
 3   restaurant_type   50 non-null     object
 4   item_ordered      50 non-null     object
 5   cart_size         50 non-null     int64
 6   recommended_item  50 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.6+ KB

       cart_size
count  50.000000
mean    2.540000
std     1.110433
min     1.000000
25%     2.000000
50%     3.000000
75%     3.000000
max     4.000000

In [9]:
df["city"].value_counts()

city
Mumbai       25
Bangalore    13
Delhi        12
Name: count, dtype: int64

In [10]:
df["order_time"].value_counts()

order_time
night      20
lunch      16
morning     7
evening     7
Name: count, dtype: int64

In [11]:
df["cart_size"].value_counts()

cart_size
3    15
4    12
1    12
2    11
Name: count, dtype: int64

In [12]:
def recommend_item(city, time, item, cart_size):

    if item == "pizza":
        return "coke"

    if item == "burger":
        return "fries"

    if item == "biryani":
        return "raita"

    if time == "morning":
        return "coffee"

    if cart_size >= 3:
        return "dessert"

    return "ice cream"

In [13]:
df["model_recommendation"] = df.apply(
    lambda x: recommend_item(
        x["city"],
        x["order_time"],
        x["item_ordered"],
        x["cart_size"]
    ),
    axis=1
)

df.head()

,user_id,city,order_time,restaurant_type,item_ordered,cart_size,recommended_item,model_recommendation
0,user_1,Mumbai,lunch,fastfood,burger,4,fries,fries
1,user_2,Mumbai,night,south indian,dosa,1,ice cream,ice cream
2,user_3,Delhi,lunch,pizza,pizza,3,coke,coke
3,user_4,Mumbai,night,indian,biryani,1,raita,raita
4,user_5,Bangalore,night,fastfood,burger,3,fries,fries

In [14]:
recommend_item("Delhi","evening","pizza",1)

'coke'