In [1]:
import pandas as pd
df = pd.read_csv("popular_food_combos_dataset.csv")
df.head()

,order_id,city,order_time,main_item,addon_item,combo,popularity_score
0,1,Delhi,lunch,biryani,raita,biryani + raita,459
1,2,Mumbai,lunch,burger,coke,burger + coke,337
2,3,Bangalore,night,burger,coke,burger + coke,256
3,4,Delhi,evening,burger,fries,burger + fries,78
4,5,Bangalore,morning,pizza,garlic bread,pizza + garlic bread,273

In [2]:
popular_combos = df.sort_values(by="popularity_score", ascending=False)
popular_combos.head(5)

,order_id,city,order_time,main_item,addon_item,combo,popularity_score
48,49,Bangalore,evening,burger,coke,burger + coke,491
52,53,Bangalore,night,pizza,coke,pizza + coke,475
33,34,Bangalore,evening,sandwich,coffee,sandwich + coffee,475
20,21,Bangalore,morning,sandwich,coffee,sandwich + coffee,469
0,1,Delhi,lunch,biryani,raita,biryani + raita,459

In [3]:
df.groupby("city")["combo"].value_counts().head(10)

city       combo
Bangalore  burger + coke           6
           burger + fries          6
           pizza + garlic bread    5
           sandwich + coffee       5
           biryani + raita         4
           pizza + coke            4
           dosa + filter coffee    1
Delhi      pizza + coke            6
           burger + fries          3
           burger + coke           2
Name: count, dtype: int64

In [4]:
def recommend_for_new_user(city):
    
    city_data = df[df["city"] == city]
    
    popular = city_data.sort_values(
        by="popularity_score",
        ascending=False
    )
    
    return popular["combo"].head(3)

In [5]:
recommend_for_new_user("Delhi")

0     biryani + raita
17       pizza + coke
23       pizza + coke
Name: combo, dtype: object